/* Auth action types */
export const AUTH_INIT = 'AUTH_INIT';
export const LOGGED_IN = 'LOGGED_IN';
export const SIGNED_UP = 'SIGNED_UP';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

export const LOGOUT = 'LOGOUT';

/* Record action types */
export const RECORD_REQUEST = 'RECORD_REQUEST';
export const RECORD_CREATE_SUCCESS = 'RECORD_CREATE_SUCCESS';
export const RECORD_CREATE_ERROR = 'RECORD_CREATE_ERROR';
export const RECORD_FETCH_SUCCESS = 'RECORD_FETCH_SUCCESS';
export const RECORD_FETCH_ERROR = 'RECORD_FETCH_ERROR';
export const RECORD_UPDATE_SUCCESS = 'RECORD_UPDATE_SUCCESS';
export const RECORD_UPDATE_ERROR = 'RECORD_UPDATE_ERROR';
export const RECORD_DELETE_SUCCESS = 'RECORD_DELETE_SUCCESS';
export const RECORD_DELETE_ERROR = 'RECORD_DELETE_ERROR';
export const SINGLE_RECORD_FETCH_SUCCESS = 'SINGLE_RECORD_FETCH_SUCCESS';

export const STATS_FETCH = 'STATS_FETCH';
export const STATS_FETCH_ERROR = 'STATS_FETCH_ERROR';
export const STATS_FETCH_SUCCESS = 'STATS_FETCH_SUCCESS';
export const USER_STATS_FETCH_SUCCESS = 'USER_STATS_FETCH_SUCCESS';

/* Toast actions */
export const CREATE_TOAST = 'CREATE_TOAST';
export const DELETE_TOAST = 'DELETE_TOAST';
